services:


  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - "3306:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - network
    healthcheck:
      test: ["CMD", "mysqladmin","ping", "-h", "localhost"]
      interval: 10s
      retries: 5
      timeout: 10s
      start_period: 20s
    env_file:
      - .env
    restart: always


  wms:
    build:
      context: .
    environment:
      FLASK_APP: wms.py
      FLASK_ENV: development
    ports:
      - "5050:5050"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - network
    env_file:
      - .env
    restart: always


networks:
  network:
    driver:  bridge